services:
  - type: web
    name: integration-middleware
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
        
  - type: web
    name: integration-platform-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://integration-middleware.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
